# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Default values for onlineboutique.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

images:
  adservice:
    # repository: 071882750948.dkr.ecr.us-east-2.amazonaws.com/11_microservices_demo/adservice
    # Overrides the image tag whose default is the chart appVersion.
    repository: 389770079035.dkr.ecr.us-east-1.amazonaws.com/11_microservices/adservice
    tag: f1069a2-134
    digest: sha256:59087efced2b130380a5c92ebf9d609e65f09362441977746962605ba1e6cfaa
  cartservice:
    repository: 389770079035.dkr.ecr.us-east-1.amazonaws.com/11_microservices/cartservice
    tag: 0d0608c-136
    digest: sha256:bb568bf85ef1e5ef4c1c67feae27920a38f6d8c35549b743fc356e485714d296
  checkoutservice:
    repository: 389770079035.dkr.ecr.us-east-1.amazonaws.com/11_microservices/checkoutservice
    tag: bcc86ad-138
    digest: sha256:1d193a9b925600fa369fefbfc7fdca1ea3ba01e452a76f6851cf6913f872b27c
  currencyservice:
    repository: 389770079035.dkr.ecr.us-east-1.amazonaws.com/11_microservices/currencyservice
    tag: ad596d7-140
    digest: sha256:0d3fb052ad233df2c5ffa03b757bd465680833260fa0bdcf377ee61e2c671d70
  emailservice:
    repository: 389770079035.dkr.ecr.us-east-1.amazonaws.com/11_microservices/emailservice
    tag: dede1c7-142
    digest: sha256:437cfc8c58d5311cf60e09e96825a2886a1e92b42336f4bc0d2ede1bd2127291
  paymentservice:
    repository: 389770079035.dkr.ecr.us-east-1.amazonaws.com/11_microservices/paymentservice
    tag: c86f163-111
    digest: sha256:9adb57a41b3c8d6eb54d612f02ab190de5dee7731ceca4804b782815cf2fcf06
  productcatalogservice:
    repository: 389770079035.dkr.ecr.us-east-1.amazonaws.com/11_microservices/productcatalogservice
    tag: 83490c6-113
    digest: sha256:a129db60e0d1c9d231f6b4cc701ffcdc1ba0d87177e2e987160060dd5dec90f7
  recommendationservice:
    repository: 389770079035.dkr.ecr.us-east-1.amazonaws.com/11_microservices/recommendationservice
    tag: 9a6008c-115
    digest: sha256:9d0e818cc7ccc9a22c1cdb5cf1c96e64cfd312fa3f28db9f64af0303e602a306
  shippingservice:
    repository: 389770079035.dkr.ecr.us-east-1.amazonaws.com/11_microservices/shippingservice
    tag: c36ec5b-117
    digest: sha256:c38e5112de10350ad554922ba4f2f335f2aa03b025dfcd4b05a969de6318df3b
  frontendservice:
    tag: 03c96db-106
    digest: sha256:e0f65d66623d8105952b07a9aacb6520e7771ffa0f10829a7f049ddcf8ec650c
  loadgeneratorservice:
    tag: 8d276b8-109
    digest: sha256:b2210053e2d3babf643249dcf013bdf2bef27b5240cbe558ac382c7b85299abf
serviceAccounts:
  # Specifies whether service accounts should be created.
  create: true
  # Annotations to add to the service accounts.
  annotations: {}
  # Annotations to add only for the cartservice app. This allows to follow the least privilege principle where only cartservice needs to connect to external database for example via Workload Identity.
  annotationsOnlyForCartservice: false
networkPolicies:
  # Specifies if the NetworkPolicies are created or not. If true, one fine granular NetworkPolicy per app is created.
  create: false
sidecars:
  # Specifies if the Sidecars are created or not. If true, one fine granular Sidecar per app is created.
  create: false
authorizationPolicies:
  # Specifies if the AuthorizationPolicies are created or not. If true, one fine granular AuthorizationPolicy per app is created.
  create: false
opentelemetryCollector:
  create: false
  name: opentelemetrycollector
  # Specifies the project id for the otel collector. If set as "PROJECT_ID" (default value), an initContainer will automatically retrieve the project id value from the metadata server.
  projectId: "PROJECT_ID"
googleCloudOperations:
  profiler: false
  tracing: false
  metrics: false
seccompProfile:
  enable: false
  type: RuntimeDefault
securityContext:
  enable: true
adService:
  create: true
  name: adservice
  resources:
    requests:
      cpu: 200m
      memory: 180Mi
    limits:
      cpu: 300m
      memory: 300Mi
cartService:
  create: true
  name: cartservice
  resources:
    requests:
      cpu: 200m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi
checkoutService:
  create: true
  name: checkoutservice
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
currencyService:
  create: true
  name: currencyservice
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
emailService:
  create: true
  name: emailservice
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
frontend:
  create: true
  name: frontend
  externalService: false
  cymbalBranding: false
  # One of: local, gcp, aws, azure, onprem, alibaba. When not set, defaults to "local" unless running in GKE, otherwise auto-sets to gcp.
  platform: aws
  singleSharedSession: false
  virtualService:
    create: false
    hosts:
      - "*"
    gateway:
      name: asm-ingressgateway
      namespace: asm-ingress
      labelKey: asm
      labelValue: ingressgateway
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
loadGenerator:
  create: true
  name: loadgenerator
  checkFrontendInitContainer: true
  resources:
    requests:
      cpu: 300m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
paymentService:
  create: true
  name: paymentservice
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
productCatalogService:
  create: true
  name: productcatalogservice
  # Specifies an extra latency to any request on productcatalogservice, by default no extra latency.
  extraLatency: ""
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
recommendationService:
  create: true
  name: recommendationservice
  resources:
    requests:
      cpu: 100m
      memory: 220Mi
    limits:
      cpu: 200m
      memory: 450Mi
shippingService:
  create: true
  name: shippingservice
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
cartDatabase:
  # Specifies the type of the cartservice's database, could be either redis or spanner.
  type: redis
  connectionString: "redis-cart:6379"
  inClusterRedis:
    create: true
    name: redis-cart
    # Uses the public redis image from Docker Hub, otherwise will use the images.repository.
    publicRepository: true
  externalRedisTlsOrigination:
    enable: false
    name: exernal-redis-tls-origination
    endpointAddress: ""
    endpointPort: ""
    certificate: ""
# @TODO: This service is not currently available in Helm.
# https://github.com/GoogleCloudPlatform/microservices-demo/tree/main/kustomize/components/shopping-assistant
shoppingAssistantService:
  create: false
  name: shoppingassistantservice
