@Library('shared_library') _

def svc = 'paymentservice'

ciPipeline(

    serviceName: svc,

    ecrRepo: '071882750948.dkr.ecr.us-east-2.amazonaws.com/11_microservices_demo/paymentservice',

    dockerCiPrebakedImage: 'nishant1994docker/currency-service-prebaked:trivy-owasp-sonar-ci-image',

    dockerCIPrebakedImageArgs: '-u root',

    programmingLanguage: 'node',

    servicePath: '.',

    buildAndTestCmd: """
        echo "=== NODE INSTALL ==="
        npm install

        echo "=== NODE BUILD ==="
        npm run build || echo "No build script found, skipping"
    """,

    sonarCmd: """
        sonar-scanner \\
          -Dsonar.projectKey=paymentservice \\
          -Dsonar.sources=. \\
          -Dsonar.host.url=\$SONAR_HOST_URL \\
          -Dsonar.login=\$SONAR_AUTH_TOKEN
    """,

    trivyScanCmd: """
        echo "=== TRIVY SCAN ==="

        trivy fs . \\
          --severity MEDIUM,LOW \\
          --format table \\
          --exit-code 0 \\
          --no-progress \\
          --cache-dir \$WORKSPACE/.trivy-cache \\
          --output trivy-report.txt
    """,

    jUnitReportPath: '',

    archiveReports: """
        trivy-report.txt
    """

)