@Library('shared_library_prod') _

def svc = 'cartservice'

ciPipeline(

    serviceName: svc,

    ecrRepo: '071882750948.dkr.ecr.us-east-2.amazonaws.com/11_microservices_demo/cartservice',

    dockerCiPrebakedImage: 'nishant1994docker/cartservice-prebaked-image:trivy-owasp',

    programmingLanguage: 'dotnet',

    servicePath: '.',

    buildAndTestCmd: """
        export HOME=\$WORKSPACE
        export DOTNET_CLI_HOME=\$WORKSPACE

        echo "=== Restore ==="
        dotnet restore

        echo "=== Build ==="
        dotnet build -c Release --no-restore
    """,

    sonarCmd: """
        export HOME=\$WORKSPACE
        export DOTNET_CLI_HOME=\$WORKSPACE

        dotnet sonarscanner begin \
            /k:"cartservice" \
            /d:sonar.host.url=\$SONAR_HOST_URL \
            /d:sonar.token=\$SONAR_AUTH_TOKEN

        dotnet build -c Release --no-restore

        dotnet sonarscanner end \
            /d:sonar.token=\$SONAR_AUTH_TOKEN
    """,

    trivyScanCmd: """
        echo "=== Trivy FS Scan ==="

        trivy fs . \
            --severity HIGH,CRITICAL \
            --format table \
            --exit-code 1 \
            --no-progress \
            --cache-dir .trivy-cache \
            --output trivy-report.txt
    """,

    jUnitReportPath: '',

    archiveReports: """
        trivy-report.txt
    """

)