apiVersion: gateway.k8s.aws/v1beta1
kind: TargetGroupConfiguration
metadata:
  #name: app-tg-config
  name: frontend-canary-tgc
  #namespace: boutique-app
spec:
  targetReference:
    name: dev-frontend-canary
  defaultConfiguration:
    targetType: ip
