apiVersion: gateway.k8s.aws/v1beta1
kind: TargetGroupConfiguration
metadata:
  #name: app-tg-config
  name: frontend-stable-tgc
  #namespace: boutique-app
spec:
  targetReference:
    name: frontend-stable
  defaultConfiguration:
    targetType: ip
