library 'shared_library_prod'

def svc = 'frontendservice'

ciPipeline(

    gitUrl: scm.userRemoteConfigs[0].url,

    serviceName: svc,

    ecrRepo: '071882750948.dkr.ecr.us-east-2.amazonaws.com/11_microservices_demo/frontendservice',

    dockerCiPrebakedImage: 'nishant1994docker/checkoutservice-prebaked:owasp-trivy-sonar-1',

    dockerCIPrebakedImageArgs: '',

    programmingLanguage: 'go',

    servicePath: 'src/frontend',

    buildAndTestCmd: """
        echo "=== GO BUILD ==="
        export GOTOOLCHAIN=auto
        go mod download
        go build -o frontendservice
    """,

    sonarCmd: """
        sonar-scanner \\
          -Dsonar.projectKey=frontendservice \\
          -Dsonar.sources=. \\
          -Dsonar.host.url=\$SONAR_HOST_URL \\
          -Dsonar.login=\$SONAR_AUTH_TOKEN
    """,

    trivyScanCmd: """
        echo "=== Trivy Scan ==="

        trivy fs . \\
          --severity MEDIUM,LOW \
          --format table \
          --exit-code 1 \
          --no-progress \
          --cache-dir \$TRIVY_CACHE_DIR \
          --output trivy-report.txt
    """,

    jUnitReportPath: '',

    archiveReports: """
        trivy-report.txt
    """

)