// @Library('shared_library_prod') _

// def svc = 'checkoutservice'

// ciPipeline(

//     serviceName: svc,

//     ecrRepo: '071882750948.dkr.ecr.us-east-2.amazonaws.com/11_microservices_demo/checkoutservice',

//     dockerCiPrebakedImage: 'nishant1994docker/checkoutservice-prebaked:owasp-trivy-sonar-1',

//     dockerCIPrebakedImageArgs: '-u root',

//     programmingLanguage: 'go',

//     servicePath: '.',

//     buildAndTestCmd: """
//         echo "=== GO BUILD ==="
//         export GOTOOLCHAIN=auto
//         go mod download
//         go build -o checkoutservice
//     """,

//     sonarCmd: """
//         sonar-scanner \\
//           -Dsonar.projectKey=checkoutservice \\
//           -Dsonar.sources=. \\
//           -Dsonar.host.url=\$SONAR_HOST_URL \\
//           -Dsonar.login=\$SONAR_AUTH_TOKEN
//     """,

//     trivyScanCmd: """
//         echo "=== Trivy Scan ==="

//         trivy fs . \\
//           --severity MEDIUM,LOW \\
//           --format table \\
//           --exit-code 1 \\
//           --no-progress \\
//           --cache-dir \$WORKSPACE/.trivy-cache \\
//           --output trivy-report.txt
//     """,

//     jUnitReportPath: '',

//     archiveReports: """
//         trivy-report.txt
//     """

// )
library 'shared_library_prod'

def svc = 'checkoutservice'

ciPipeline(

    gitUrl: scm.userRemoteConfigs[0].url,

    serviceName: svc,

    servicePath: 'src/checkoutservice',

    ecrRepo: '071882750948.dkr.ecr.us-east-2.amazonaws.com/11_microservices_demo/checkoutservice',

    dockerCiPrebakedImage: 'nishant1994docker/checkoutservice-prebaked:owasp-trivy-sonar-awscli-dockercli-ci-image',

    dockerCIPrebakedImageArgs: '-v /var/run/docker.sock:/var/run/docker.sock -v /usr/bin/docker:/usr/bin/docker --group-add 110',
    
    programmingLanguage: 'go',

    buildAndTestCmd: """
        set -e

        echo "=== GO BUILD START ==="

        go mod download
        go build -o checkoutservice

        echo "=== GO BUILD END ==="
    """,

    sonarCmd: """
        set -e

        echo "=== SONAR START ==="

        sonar-scanner \
          -Dsonar.projectKey=checkoutservice \
          -Dsonar.sources=. \
          -Dsonar.host.url=\$SONAR_HOST_URL \
          -Dsonar.login=\$SONAR_AUTH_TOKEN

        echo "=== SONAR END ==="
    """,

    trivyScanCmd: """
        set -e

        echo "=== TRIVY SCAN START ==="

        trivy fs . \
          --severity MEDIUM,LOW \
          --format table \
          --exit-code 1 \
          --no-progress \
          --cache-dir \$TRIVY_CACHE_DIR \
          --output trivy-report.txt

        echo "=== TRIVY SCAN END ==="
    """,

    jUnitReportPath: '',

    archiveReports: 'trivy-report.txt'
)