// // @Library('shared_library_prod') _
// library 'shared_library_prod'
// def svc = 'adservice'

// ciPipeline(
//     gitUrl: scm.userRemoteConfigs[0].url,
//     serviceName: svc,
//     ecrRepo: '071882750948.dkr.ecr.us-east-2.amazonaws.com/11_microservices_demo/adservice',
//     dockerCiPrebakedImage: 'nishant1994docker/adservice-prebaked:trivy_owasp',
//     dockerCIPrebakedImageArgs: '-v $HOME/.gradle:/home/gradle/.gradle',
//     programmingLanguage: 'java',
//     servicePath: 'src/adservice',

//     buildAndTestCmd: """
//             chmod +x ./gradlew

//                     ./gradlew dependencies --no-daemon || true

//                     ./gradlew clean build \
//                         -x verifyGoogleJavaFormat \
//                         -x distZip \
//                         -x distTar \
//                         --no-daemon
//              """,
//     jUnitReportPath: 'build/test-results/test/*.xml',
//     sonarCmd: """
//         export SONAR_USER_HOME=/tmp/.sonar
//                     ./gradlew sonar \
//                     -Dsonar.projectKey=adservice \
//                     -Dsonar.host.url=\$SONAR_HOST_URL \
//                     -Dsonar.token=\$SONAR_AUTH_TOKEN
//     """,
//     trivyScanCmd: """
//             mkdir -p \$TRIVY_CACHE_DIR

//             trivy fs . \
//             --db-repository public.ecr.aws/aquasecurity/trivy-db \
//             --cache-dir \$TRIVY_CACHE_DIR \
//             --format table \
//             --severity LOW,MEDIUM \
//             --exit-code 1 \
//             --output trivy-report.txt
//      """,

//      archiveReports: """
//                 dependency-check-report.xml,
//                     trivy-report.txt,
//                     build/reports/**,
//                     build/test-results/**,
//                     build/jacoco/**
//                 """
 
// )


library 'shared_library_prod'

def svc = 'adservice'

ciPipeline(

    gitUrl: scm.userRemoteConfigs[0].url,

    serviceName: svc,

    ecrRepo: '071882750948.dkr.ecr.us-east-2.amazonaws.com/11_microservices_demo/adservice',

    dockerCiPrebakedImage: 'nishant1994docker/adservice-prebaked:trivy_owasp',
    dockerCIPrebakedImageArgs: '-v /var/run/docker.sock:/var/run/docker.sock -v /usr/bin/docker:/usr/bin/docker -v /usr/local/bin/aws:/usr/local/bin/aws -v /usr/local/aws-cli:/usr/local/aws-cli
 --group-add 110',

    programmingLanguage: 'java',

    servicePath: 'src/adservice',

    buildAndTestCmd: """
            echo "=== ADSERVICE BUILD ==="

            chmod +x ./gradlew

            ./gradlew dependencies --no-daemon || true

            ./gradlew clean build \\
                -x verifyGoogleJavaFormat \\
                -x distZip \\
                -x distTar \\
                --no-daemon

            echo "=== ADSERVICE BUILD END ==="
    """,

    jUnitReportPath: 'build/test-results/test/*.xml',

    sonarCmd: """
            echo "=== SONAR SCAN ==="

            export SONAR_USER_HOME=/tmp/.sonar

            ./gradlew sonar \\
                -Dsonar.projectKey=adservice \\
                -Dsonar.host.url=\$SONAR_HOST_URL \\
                -Dsonar.token=\$SONAR_AUTH_TOKEN

            echo "=== SONAR SCAN END ==="
    """,

    trivyScanCmd: """
            echo "=== TRIVY SCAN (ADSERVICE) ==="

            mkdir -p \$TRIVY_CACHE_DIR

            trivy fs . \\
              --db-repository public.ecr.aws/aquasecurity/trivy-db \\
              --cache-dir \$TRIVY_CACHE_DIR \\
              --severity LOW,MEDIUM \\
              --format table \\
              --exit-code 0 \\
              --output trivy-adservice-report.txt

            echo "=== TRIVY SCAN END ==="
    """,

    archiveReports: """
            trivy-adservice-report.txt,
            dependency-check-report.xml,
            build/reports/**,
            build/test-results/**,
            build/jacoco/**
    """
)