@Library('shared_library_prod') _

def svc = 'adservice'

ciPipeline(

    serviceName = svc,
    ecrRepo: '071882750948.dkr.ecr.us-east-2.amazonaws.com/11_microservices_demo/adservice',
    dockerCiPrebakedImage: 'nishant1994docker/adservice-prebaked:trivy_owasp',
    dockerCIPrebakedImageArgs: '-v $HOME/.gradle:/home/gradle/.gradle',
    programmingLanguage: 'java',
    servicePath: '.',

    buildAndTestCmd: """
            chmod +x ./gradlew

                    ./gradlew dependencies --no-daemon || true

                    ./gradlew clean build \
                        -x verifyGoogleJavaFormat \
                        -x distZip \
                        -x distTar \
                        --no-daemon
             """,
    jUnitReportPath: 'build/test-results/test/*.xml',
    sonarCmd: """
        export SONAR_USER_HOME=/tmp/.sonar
                    ./gradlew sonar \
                    -Dsonar.projectKey=adservice \
                    -Dsonar.host.url=\$SONAR_HOST_URL \
                    -Dsonar.token=\$SONAR_AUTH_TOKEN
                    '''
    """,
    trivyScanCmd: """
            trivy fs . \
                --db-repository public.ecr.aws/aquasecurity/trivy-db \
                --cache-dir \$WORKSPACE/trivy-cache \
                --format table \
                --severity LOW,MEDIUM \
                --exit-code 1 \
                --output trivy-report.txt
     """,

     archiveReports: """
                dependency-check-report.xml,
                    trivy-report.txt,
                    build/reports/**,
                    build/test-results/**,
                    build/jacoco/**
                """
 
)
