library 'shared_library_prod'

def svc = 'emailservice'

ciPipeline(

    gitUrl: scm.userRemoteConfigs[0].url,

    serviceName: svc,

    ecrRepo: '071882750948.dkr.ecr.us-east-2.amazonaws.com/11_microservices_demo/emailservice',

    dockerCiPrebakedImage: 'nishant1994docker/email-service-prebaked:trivy-owasp-sonar-awscli-docker-ci-image',

    dockerCIPrebakedImageArgs: '-v /var/run/docker.sock:/var/run/docker.sock -v /usr/bin/docker:/usr/bin/docker --group-add 110',

    programmingLanguage: 'python',

    servicePath: 'src/emailservice',

    buildAndTestCmd: """
        echo "=== EMAIL SERVICE BUILD ==="

        python3 -m pip install --upgrade pip
        pip install -r requirements.txt

        echo "Build step completed (no compilation needed for Python)"
    """,

    sonarCmd: """
        sonar-scanner \\
          -Dsonar.projectKey=emailservice \\
          -Dsonar.sources=. \\
          -Dsonar.host.url=\$SONAR_HOST_URL \\
          -Dsonar.login=\$SONAR_AUTH_TOKEN
    """,

    trivyScanCmd: """
        echo "=== TRIVY SCAN (EMAIL SERVICE) ==="

          trivy fs . \\
          --severity MEDIUM,LOW \\
          --format table \\
          --exit-code 0 \\
          --no-progress \\
          --cache-dir \$TRIVY_CACHE_DIR \\
          --output trivy-report.txt

        echo "=== TRIVY SCAN END ==="
    """,

    jUnitReportPath: '',

    archiveReports: """
        trivy-email-report.txt
    """

)