
adService:
  replicas: 2

cartService:
  replicas: 2

checkoutService:
  replicas: 2

currencyService:
  replicas: 2

emailService:
  replicas: 2

frontend:
  replicas: 5

loadGenerator:
  replicas: 3

paymentService:
  replicas: 2

productCatalogService:
  replicas: 2


recommendationService:
  replicas: 2


shippingService:
  replicas: 2


cartDatabase:
  # Specifies the type of the cartservice's database, could be either redis or spanner.
  type: redis
  connectionString: "redis-cart:6379"
  inClusterRedis:
    create: true
    name: redis-cart
    # Uses the public redis image from Docker Hub, otherwise will use the images.repository.
    publicRepository: true
  externalRedisTlsOrigination:
    enable: false
    name: exernal-redis-tls-origination
    endpointAddress: ""
    endpointPort: ""
    certificate: ""

# @TODO: This service is not currently available in Helm.
# https://github.com/GoogleCloudPlatform/microservices-demo/tree/main/kustomize/components/shopping-assistant
shoppingAssistantService:
  create: false
  name: shoppingassistantservice
